### ISSUE TITLE
Import/Rest options doesnt work.

### ISSUE THREAD

**Issue by windowos** [reduxframework/redux-framework-4#148]
## Support Hash
Your page shows 404 https://docs.redux.io/core/generating-a-support-hash

## Steps to reproduce

Reset theme options in your them -  you will get amply fields for any kind of data https://prnt.sc/tzfm9b
Import also import nothing. It doesn't work.

## Expected Behavior
Resetting should display default data I write on the config file.
Import should set data from your json file 

## Actual Behavior
I made 20 themes with Redux for 4 years. After updating to Redux 4 import and defaults stopped to work.
Nothing else I can add. Import doesn't work. Defaults doesn't work for any kind of fields.

## Any Error Details (PHP/JavaScript)
5.6, 7.1, 7.3 No errors on the console https://prnt.sc/tzfnfs

**Comment by dovy** [comment]
This has actually been fixed here in the repo. A silent release will be pushed later today. Thanks for reporting it!

**Comment by windowos** [comment]
Import still doesnt work. Checked on multiple websites. https://prnt.sc/ucyvmk

**Comment by dovy** [comment]
Boo.

**Comment by dovy** [comment]
Fixed. The release will go out today or tomorrow. This was a nasty bug that we had fixed, but because of PHPCS we kept hitting issues. Thank you for the patience.
